config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :teacher do
    resources :courses, only: %i(index show) do
      resources :lectures, only: %i(show) do
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :code, :name, presence: true
  validates :code, :name, uniqueness: true

  has_many :lectures
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  validates :name, :semester, presence: true
  validates :name, uniqueness: { scope: :knowledges_category }
  validates :semester, acceptance: { accept: [1, 2, 3, 4] }

  belongs_to :knowledges_category
end

app/models/knowledges_category.rb
class KnowledgesCategory < ApplicationRecord
  validates :code, :name, presence: true
  validates :code, uniqueness: true

  has_many :children, class_name: "KnowledgesCategory",
                      foreign_key: "parent_id"

  belongs_to :parent, class_name: "KnowledgesCategory", optional: true

  has_many :skills_cat_knowledges_cat_links
  has_many :skills_categories, through: :skills_cat_knowledges_cat_links

  has_many :knowledges_category_skill_links
  has_many :skills, through: :knowledges_category_skill_links

  has_many :knowledges

end

app/models/knowledges_category_skill_link.rb
class KnowledgesCategorySkillLink < ApplicationRecord
  belongs_to :knowledges_category
  belongs_to :skill
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :course
  validates :code, :name, presence: true
  validates :code, :name, uniqueness: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :skills_category }

  belongs_to :skills_category

  has_many :knowledges_category_skill_links
  has_many :knowledges_categories, through: :knowledges_category_skill_links
end

app/models/skills_cat_knowledges_cat_link.rb
class SkillsCatKnowledgesCatLink < ApplicationRecord
  belongs_to :skills_category
  belongs_to :knowledges_category
end

app/models/skills_category.rb
class SkillsCategory < ApplicationRecord
  validates :code, :name, presence: true
  validates :code, uniqueness: true

  has_many :children, class_name: "SkillsCategory",
                      foreign_key: "parent_id"

  belongs_to :parent, class_name: "SkillsCategory", optional: true

  has_many :skills_cat_knowledges_cat_links
  has_many :knowledges_categories, through: :skills_cat_knowledges_cat_links

  has_many :skills

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teacher/base_controller.rb
class Teacher::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_teacher!
  include Pundit

  after_action :verify_authorized, unless: :skip_pundit?
  after_action :verify_policy_scoped, unless: :skip_pundit?

  def pundit_user
    current_teacher
  end

  layout 'teacher'

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?teacher)|(^pages$)/
  end

end

app/controllers/teacher/courses_controller.rb
class Teacher::CoursesController < Teacher::BaseController

  def index
    if policy_scope([:teacher, Course])
      @courses = policy_scope([:teacher, Course])
    else
      user_not_authorized
    end
  end

  def show
    @course = Course.find(params[:id])
    authorize([:teacher, @course])
  end

  # def move_higher
  #   @course = Course.find(params[:course_id])
  #   @course.move_higher
  #   redirect_to admin_courses_url
  # end

  # def move_lower
  #   @course = Course.find(params[:course_id])
  #   @course.move_lower
  #   redirect_to admin_courses_url
  # end
end

app/controllers/teacher/lectures_controller.rb
class Teacher::LecturesController < Teacher::BaseController
  before_action :set_lecture, only: [:show, :edit, :update]

  def index
    if policy_scope([:teacher, Lecture])
      @lectures = policy_scope([:teacher, Lecture])
    else
      user_not_authorized
    end
  end

  def show
  end

  # def edit
  # end

  # def update
  #   if @lecture.update(lecture_params)
  #     redirect_to teacher_course_lecture_url(@lecture.course, @lecture), notice: 'Lecture was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # def move_higher
  #   @lecture = Lecture.find(params[:lecture_id])
  #   @lecture.move_higher
  #   redirect_to teacher_course_lectures_url(@lecture.course)
  # end

  # def move_lower
  #   @lecture = Lecture.find(params[:lecture_id])
  #   @lecture.move_lower
  #   redirect_to teacher_course_lectures_url(@lecture.course)
  # end

  private

  def set_lecture
    @lecture = Lecture.find(params[:id])
    authorize([:teacher, @lecture])
  end

  def lecture_params
    params.require(:lecture).permit(:name, :course_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/teacher.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TSI/Teacher</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Courses", teacher_courses_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-ea">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if teacher_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://raw.githubusercontent.com/EphemeAir/rails-templates/master/logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_teacher_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_teacher_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teacher/courses/index.html.erb
<h1>Courses</h1>

<ul>
  <% @courses.each do |course| %>
    <li>
      <p>
        <h2><%= link_to course.name, teacher_course_path(course) %></h2>
        <% if course.lectures.any? %>
          <h3>Lectures</h3>
          <ol>
            <% course.lectures.each do |lecture| %>
              <li>
                <% if lecture.content %>
                  <%= link_to lecture.name, asset_path(lecture.content), target: "_blank" %>
                <% else %>
                  <%= lecture.name %>
                <% end %>
              </li>
            <% end %>
          </ol>
        <% end %>
        <% if course.lectures.any? %>
          <h3>Lectures</h3>
          <ol>
            <% course.lectures.each do |lecture| %>
              <li>
                <% if lecture.content %>
                  <%= link_to lecture.name, asset_path(lecture.content), target: "_blank" %>
                <% else %>
                  <%= lecture.name %>
                <% end %>
              </li>
            <% end %>
          </ol>
        <% end %>
      </p>
    </li>
  <% end %>
</ul>

app/views/teacher/courses/show.html.erb
<h1><%= @course.name %></h1>

<% if @course.lectures.any? %>
  <h2>Lectures</h2>
  <% @course.lectures.each do |lecture| %>
    <ol>
      <%= link_to lecture.name, teacher_course_lecture_path(@course, lecture) %>
    </ol>
  <% end %>
<% else %>
  <p>coming soon page</p>
<% end %>

app/views/teacher/lectures/_form.html.erb
<%= simple_form_for(@lecture, url: teacher_course_lecture_url(@lecture.course, @lecture)) do |f| %>

  <div class="form-inputs">
    <%= f.association :course %>
    <%= f.input :name %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/teacher/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', course: @lecture.course, lecture: @lecture %>

<%= link_to 'Show', teacher_course_lecture_path(@lecture.course, @lecture) %> |
<%= link_to 'Back', teacher_course_lectures_path(@lecture.course) %>

app/views/teacher/lectures/index.html.erb
<h1><%= @lectures.first.course.name %></h1>

<h2>Lectures</h2>
<ul>
  <% @lectures.each do |lecture| %>
    <li>
      <p>
        <%= link_to lecture.name, teacher_course_lecture_path(lecture.course, lecture) %>
      </p>
    </li>
  <% end %>
</ul>

app/views/teacher/lectures/show.html.erb
<h1><%= @lecture.course.name %></h1>

<h2><%= @lecture.name %></h2>

<% if @lecture.content %>
  <p><%= link_to "content", asset_path(@lecture.content), target: "_blank" %></p>
<% end %>